- name: 'carl-replacement'
  description: Issues that allows us to replace CarlBot
  color: '9C004F'
- name: 'approved'
  description: Issues and PRs that have been approved.
  color: '8CE098'

- name: 'question'
  description: Issues that asks a question.
  color: 'D4C5F9'
- name: 'feature'
  description: Issues/PRs that requests/adds a new feature.
  color: '0052CC'
- name: 'enhancement'
  description: Issues/PRs that requests/adds an improvement to an existing feature.
  color: '5319E7'
- name: 'bug'
  description: Issues/PRs that reports or fixes a bug.
  color: 'D93F0B'

- name: 'high priority'
  description: Issues that must be fixed or PRs that must be finished and merged with MAXIMUM PRIORITY.
  color: 'F45B0E'
- name: 'medium priority'
  description: Issues that must be fixed or PRs that must be finished and merged with medium priority.
  color: 'FBCA04'
- name: 'low priority'
  description: Issues that must be fixed or PRs that must be finished and merged with low priority.
  color: '9CEB34'

- name: 'hard'
  description: Issues that are quite complex to finish.
  color: 'E0B325'
- name: 'not easy'
  description: Issues that are not easy to finish.
  color: 'DDE025'
- name: 'easy'
  description: Issues that are easy to finish.
  color: 'C3E025'
- name: 'trivial'
  description: Issues that are very easy to finish.
  color: '85E025'
