name: Move priority card
on:
  issues:
    types:
      - labeled
jobs:
  move-priority-card:
    if: ${{ github.event.label.name == "priority: high" && contains(github.event.issue.labels.*.name, "status: approved") }}
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: MonkaBot
          column: Priority
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
